<a href="https://colab.research.google.com/github/siddheshmisale/Kaggle-Course-Learnings/blob/main/Python_Basics_Lambda%2C_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Lambdas in Filter

sequences = [10,2,8,7,5,4,3,11,0, 1]
filtered_result = filter (lambda x: x > 4, sequences) 
print(list(filtered_result))


#Immediately Callable lambda

x="some kind of a useless lambda"
(lambda x : print(x))(x)


sequences = [10,2,8,7,5,4,3,11,0, 1]
filtered_result = map (lambda x: x*x, sequences) 
print(list(filtered_result))


from functools import reduce
sequences = [1,2,3,4,5]
product = reduce (lambda x, y: x*y, sequences)
print(product)


def make_pretty(func):
    def inner():
        print("I got decorated")
        func()
    return inner


def ordinary():
    print("I am ordinary")


ordinary()

# let's decorate this ordinary function
pretty = make_pretty(ordinary)
pretty()



@make_pretty
def ordinary():
    print("I am ordinary")

# def ordinary():
#     print("I am ordinary")
# ordinary = make_pretty(ordinary)    


ordinary()


# A new list with memory location
myList = ["Orange", "Apple","Grapes"]

# Function to add an item to the list
def addItem(myTempList):
    myTempList.append("Mango")
    print(myTempList)
# Print the original list
addItem(myList)
print(myList)

myInt = 45
print("myInt",id(myInt))
mySecondInt = myInt
print("mySecondInt",id(mySecondInt))
myInt = 10
print("myInt",id(myInt))
myInt += 23
print("myInt",id(myInt))


myInt = 5
def addNumber(myNum):
    myNum += 10
    print(myNum)
    print("Memory Address of myNum",id(myNum))
    
addNumber(myInt)
print(myInt)
print("Memory Address of myInt",id(myInt))

NUMPY


In [19]:
import numpy as np
a = np.array([1,2,3])

array([1, 2, 3])

In [26]:
a**2


array([1, 4, 9])

In [28]:
np.sqrt(a)
np.exp(a)
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [29]:
#dot product

a = np.array([1,2,3])
b = np.array([4,5,6])
dot = 0
for i,j in zip(a,b):
  dot += i*j

dot


32

In [32]:
np.sum(a*b)


32

In [31]:
(a*b).sum()

32

In [33]:
np.dot(a,b)

32

In [35]:
(a).dot(b)

32

In [36]:
a @ b

32

In [37]:
#mag of vector:

amag = np.linalg.norm(a)
bmag = np.linalg.norm(b)

In [ ]:
#How to create a boolean array?

np.full()